apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops-hw
data:
  ENV: "dev"
  LOG_LEVEL: "INFO"
  S3_ENDPOINT_URL: "http://minio:9000"
  S3_BUCKET: "mlops"
  DVC_REMOTE: "s3://mlops"
  CLEARML_API_HOST: "http://clearml-webserver:8080"
