apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops-hw
type: Opaque
data:
  S3_ACCESS_KEY_ID: bWluaW9hZG1pbg==           # minioadmin
  S3_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==       # minioadmin
  CLEARML_API_ACCESS_KEY: Y2hhbmdlbWU=         # changeme
  CLEARML_API_SECRET_KEY: Y2hhbmdlbWU=         # changeme
