apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-ui
  namespace: mlops-hw
spec:
  replicas: 1
  selector:
    matchLabels: { app: mlops-ui }
  template:
    metadata:
      labels: { app: mlops-ui }
    spec:
      containers:
        - name: ui
          image: mlops-hw/ui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_BASE_URL
              value: "http://mlops-api.mlops-hw.svc.cluster.local:8000"
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-ui
  namespace: mlops-hw
spec:
  selector: { app: mlops-ui }
  type: NodePort
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30851
